version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-8
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Yunshu@123
      MYSQL_DATABASE: appdb
      TZ: Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:


