version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Standard"
      MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AS"

    ports:
      - "127.0.0.1:1433:1433"

    volumes:
      - ./data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup

    deploy:
      resources:
        limits:
          memory: 4G
